package com.fitconnect.bookingservice;
import org.junit.jupiter.api.*; import org.mockito.*; import java.math.BigDecimal; import java.time.LocalDateTime; import java.util.*; import static org.junit.jupiter.api.Assertions.*; import static org.mockito.Mockito.*;
class BookingServiceTest {
 BookingRepository repo=mock(BookingRepository.class);ClassClient classes=mock(ClassClient.class);PaymentClient payments=mock(PaymentClient.class);NotificationClient notifications=mock(NotificationClient.class);BookingService service=new BookingService(repo,classes,payments,notifications);
 @BeforeEach void setup(){when(repo.save(any())).thenAnswer(i->{Booking b=i.getArgument(0);b.setId(1L);return b;});when(notifications.send(any())).thenReturn(Map.of());}
 @Test void shouldCreateBooking_whenSpotsAvailable(){Contracts.ClassView c=new Contracts.ClassView(101L,"Yoga","Marie","Paris","YOGA","BEGINNER",10,5,new BigDecimal("20"),LocalDateTime.now().plusDays(3),"SCHEDULED");when(classes.get(101L)).thenReturn(c);Booking b=service.create(new Contracts.CreateBooking(1L,"john@example.com","John Doe",101L,2));assertEquals(Booking.Status.PENDING_PAYMENT,b.getStatus());assertEquals(new BigDecimal("40"),b.getTotalAmount());verify(classes).increment(101L,2);}
 @Test void shouldThrowException_whenNoSpotsAvailable(){Contracts.ClassView c=new Contracts.ClassView(101L,"Yoga","Marie","Paris","YOGA","BEGINNER",10,9,new BigDecimal("20"),LocalDateTime.now().plusDays(3),"SCHEDULED");when(classes.get(101L)).thenReturn(c);assertThrows(IllegalStateException.class,()->service.create(new Contracts.CreateBooking(1L,"john@example.com","John Doe",101L,2)));verify(classes,never()).increment(anyLong(),anyInt());verify(repo,never()).save(any());}
 @Test void shouldRejectConfirm_whenPaymentDeadlinePassed(){Booking b=Booking.builder().id(6L).status(Booking.Status.PENDING_PAYMENT).paymentDeadline(LocalDateTime.now().minusMinutes(1)).build();when(repo.findById(6L)).thenReturn(Optional.of(b));assertThrows(IllegalStateException.class,()->service.confirm(6L,new Contracts.ConfirmBooking(Contracts.PaymentMethod.CREDIT_CARD,"1234","txn")));verifyNoInteractions(payments);}
 @Test void shouldRejectCancel_whenCancellationDeadlinePassed(){Booking b=Booking.builder().id(7L).status(Booking.Status.CONFIRMED).cancellationDeadline(LocalDateTime.now().minusMinutes(1)).build();when(repo.findById(7L)).thenReturn(Optional.of(b));assertThrows(IllegalStateException.class,()->service.cancel(7L));verifyNoInteractions(payments);verify(classes,never()).decrement(anyLong(),anyInt());}
 @Test void shouldCancelBookingAndRefund_whenWithinDeadline(){Booking b=Booking.builder().id(5L).bookingReference("BK-TEST").userId(1L).userEmail("john@example.com").classId(101L).className("Yoga").numberOfSpots(2).status(Booking.Status.CONFIRMED).cancellationDeadline(LocalDateTime.now().plusHours(2)).build();when(repo.findById(5L)).thenReturn(Optional.of(b));when(payments.byBooking(5L)).thenReturn(new Contracts.PaymentView(8L,"PAY-X",5L,"SUCCESS"));service.cancel(5L);assertEquals(Booking.Status.CANCELLED,b.getStatus());verify(payments).refund(8L);verify(classes).decrement(101L,2);}
}
